// Edit this file to change the game without touching logic.
const questions = [
  {
    question: "VAR01",
    gif: "https://media.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif",
    correct_answer: "Penal",
    possible_answers: {
      button1: "No es falta",
      button2: "Penal",
    },
  },
  {
    question: "VAR02",
    gif: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",
    correct_answer: "Roja",
    possible_answers: {
      button1: "No es falta",
      button2: "Falta",
      button3: "Amarilla",
      button4: "Roja",
    },
  },

  // --- DUPLICATE + EDIT to reach 20 ---
  {
    question: "VAR03",
    gif: "https://media.giphy.com/media/xT0GqFhyNd0Wmfo6sM/giphy.gif",
    correct_answer: "Offside",
    possible_answers: { button1: "Gol válido", button2: "Offside" },
  },
  {
    question: "VAR04",
    gif: "https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif",
    correct_answer: "Amarilla",
    possible_answers: { button1: "Siga", button2: "Falta", button3: "Amarilla", button4: "Roja" },
  },
  { question: "VAR05", gif: "https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif", correct_answer: "Penal",
    possible_answers: { button1: "No es falta", button2: "Penal" } },
  { question: "VAR06", gif: "https://media.giphy.com/media/l0HlNQ03J5JxX6lva/giphy.gif", correct_answer: "No es falta",
    possible_answers: { button1: "No es falta", button2: "Falta" } },
  { question: "VAR07", gif: "https://media.giphy.com/media/26BRQTezZrKak4BeE/giphy.gif", correct_answer: "Gol válido",
    possible_answers: { button1: "Gol válido", button2: "Anular" } },
  { question: "VAR08", gif: "https://media.giphy.com/media/3o7TKtnuHOHHUjR38Y/giphy.gif", correct_answer: "Roja",
    possible_answers: { button1: "Amarilla", button2: "Roja" } },
  { question: "VAR09", gif: "https://media.giphy.com/media/l0Exk8EUzSLsrErEQ/giphy.gif", correct_answer: "Falta",
    possible_answers: { button1: "Siga", button2: "Falta" } },
  { question: "VAR10", gif: "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyU/giphy.gif", correct_answer: "Penal",
    possible_answers: { button1: "No es falta", button2: "Penal" } },
  { question: "VAR11", gif: "https://media.giphy.com/media/26FPy3QZQqGtDcrja/giphy.gif", correct_answer: "Offside",
    possible_answers: { button1: "Gol válido", button2: "Offside" } },
  { question: "VAR12", gif: "https://media.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif", correct_answer: "Amarilla",
    possible_answers: { button1: "No es falta", button2: "Falta", button3: "Amarilla", button4: "Roja" } },
  { question: "VAR13", gif: "https://media.giphy.com/media/l0MYKDrJ2x7wJtTGM/giphy.gif", correct_answer: "Gol válido",
    possible_answers: { button1: "Gol válido", button2: "Anular" } },
  { question: "VAR14", gif: "https://media.giphy.com/media/3o7aD4kZn5k0SEvPmo/giphy.gif", correct_answer: "Falta",
    possible_answers: { button1: "Siga", button2: "Falta" } },
  { question: "VAR15", gif: "https://media.giphy.com/media/26BRuo6sLetdllPAQ/giphy.gif", correct_answer: "Roja",
    possible_answers: { button1: "Amarilla", button2: "Roja" } },
  { question: "VAR16", gif: "https://media.giphy.com/media/l0ExncehJzexFpRHq/giphy.gif", correct_answer: "Penal",
    possible_answers: { button1: "No es falta", button2: "Penal" } },
  { question: "VAR17", gif: "https://media.giphy.com/media/3o7aD2J8lqJZ8rZp3a/giphy.gif", correct_answer: "No es falta",
    possible_answers: { button1: "No es falta", button2: "Falta" } },
  { question: "VAR18", gif: "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif", correct_answer: "Offside",
    possible_answers: { button1: "Gol válido", button2: "Offside" } },
  { question: "VAR19", gif: "https://media.giphy.com/media/3oEjHP8ELRNNlnlLGM/giphy.gif", correct_answer: "Amarilla",
    possible_answers: { button1: "No es falta", button2: "Falta", button3: "Amarilla", button4: "Roja" } },
  { question: "VAR20", gif: "https://media.giphy.com/media/3o7aD7lq0tWk5mXzHy/giphy.gif", correct_answer: "Gol válido",
    possible_answers: { button1: "Gol válido", button2: "Anular" } },
];